apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup-ns.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backup-ns.labels" . | nindent 4 }}
data:
  {{- with .Values.envData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}