{{- if .Values.roleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "backup-ns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backup-ns.labels" . | nindent 4 }}
roleRef:
  apiGroup: {{ .Values.roleBinding.roleRef.apiGroup }}
  kind: {{ .Values.roleBinding.roleRef.kind }}
  name: {{ .Values.roleBinding.roleRef.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "backup-ns.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}