apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "backup-ns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backup-ns.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: a3cloud-backup
subjects:
  - kind: ServiceAccount
    name: {{ include "backup-ns.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}