name: Build & Test

on:
  push:
    branches:
      - "**"

env:
  DOCKER_ENV_FILE: ".github/workflows/docker.env"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: setup@kindconfig
        run: |
          kind_in="${{ github.workspace }}/.github/config/kind.yml.in"
          kind_out="${{ github.workspace }}/.github/config/kind.yml"
          hostip=$(sh .github/scripts/get-host-ip.sh)
          sed "s/127.0.0.1/$hostip/g" $kind_in > $kind_out

      - name: setup@kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          config: .github/config/kind.yml
          version: v0.24.0
          name: backup-ns
          image: kindest/node:v1.28.13 # ensure same as in Makefile

      - name: setup@kubeconfig
        run: |
          hostip=$(sh .github/scripts/get-host-ip.sh)
          sed "s/127.0.0.1/$hostip/g" $HOME/.kube/config > ${{ github.workspace }}/kubeconfig.yml

      - name: Build the Docker image
        run: docker build --target builder --file Dockerfile --tag ${IMAGE_NAME}-builder:${GITHUB_SHA:8} .

      - name: Create container
        run: docker run -d --env-file $DOCKER_ENV_FILE --name=builder -it ${IMAGE_NAME}-builder:${GITHUB_SHA:8}

      - name: Init Kind
        run: docker exec builder bash /app/test/init_kind.sh

      - name: make tidy
        run: docker exec builder make tidy

      - name: make build
        run: docker exec builder make build

      - name: make test
        run: docker exec builder make test

      - name: Stop container
        if: ${{ always() }}
        run: docker stop builder

      - name: Remove container
        if: ${{ always() }}
        run: docker rm builder

  publish:
    if: github.event_name == 'tag' || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'))
    needs:
      - build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
